weights = {
    "Vệ sinh chưa tốt": -5,
    "Cờ bạc, hút thuốc, uống rượu, bia": -20,
    "Cúp tiết, SHDC, SHL": -5,
    "Vi phạm pháp luật": -20,
    "Vi phạm kiểm tra": -5,
    "Phá hoại tài sản": -20,
    "Vô lễ, đánh nhau": -20,
    "Không đội nón bảo hiểm hoặc sai quy cách": -5,
    "Sử dụng điện thoại trong giờ học": -3,
    "Nghỉ học không phép": -4,
    "Vi phạm học tập": -3,
    "Mất trật tự": -3,
    "Nhuộm tóc, son môi, sơn móng": -3,
    "Nói tục": -3,
    "Đi trễ": -2,
    "Không đồng phục": -2,
    "Tóc dài hoặc cắt kiểu không phù hợp": -2,
    "Đi cổng giáo viên": -2,
    "Chạy xe trong sân": -2,
    "Mang dép lào": -2,
    "Nghỉ học có phép": -1,
    "Điểm 8": +3,
    "Điểm 9": +4,
    "Điểm 10": +5,
    "Tiết học tốt": +50,
    "Không tham gia phong trào": -20,
    "Điểm cộng": +1,
    "Điểm thưởng": +1
}
